#!/usr/bin/env bash

SCRIPT_PATH=$(dirname -- "${BASH_SOURCE[0]}") || {
  echo "Could not find the script directory. Exiting."
  exit 1
}
. "$SCRIPT_PATH"/shared.sh

require_cli

gg-cli get-debug-password
