---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This is simple video capture component written in bash."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/bash-capture-loop.zip"
        Unarchive: ZIP
    Lifecycle:
      Install:
        Script: "apt-get install -y linux-generic v4l-utils"
        RequiresPrivilege: true
      # chmod is required since the ZIP archive will not maintain the executable bit
      Run: "chmod +x {artifacts:decompressedPath}/bash-capture-loop/capture-loop &&
            chmod +x {artifacts:decompressedPath}/bash-capture-loop/capture-one &&
            {artifacts:decompressedPath}/bash-capture-loop/capture-loop"
